version: "3.7"
services:
  web:
    build:
      context: web
      dockerfile: Dockerfile.dev
      args:
        REACT_APP_VERSION: local+devcontainer
    image: labflow/webapp-dev:latest
    tty: true
    environment:
      - "CHOKIDAR_USEPOLLING=true"
    volumes:
      - ./web:/app
      - /app/node_modules
  server:
    build:
      context: server
      args:
        REACT_APP_VERSION: local+devcontainer
    command: uvicorn main:app --port 5000 --host 0.0.0.0 --timeout-keep-alive 120 --reload --log-level trace
    environment:
      - "SQLALCHEMY_ECHO=True"
    volumes:
      - ./server:/app