"""Changes demo_run_permissions key format.

Revision ID: 07d5166c9675
Revises: ad19827e762c
Create Date: 2020-07-12 23:51:15.065624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07d5166c9675'
down_revision = 'ad19827e762c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('demo_run_permission', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('demo_run_permission', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    # ### end Alembic commands ###
