"""Adds demo_run.

Revision ID: 2bee1dfc00e3
Revises: 089f276fe6a9
Create Date: 2020-07-12 22:40:48.358021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bee1dfc00e3'
down_revision = '089f276fe6a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('demo_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('demo_run')
    # ### end Alembic commands ###
