"""Adds user, run, protocol versioning.

Revision ID: 30b42e5a4109
Revises: 849bf8cfb979
Create Date: 2020-11-01 04:09:14.611614

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '30b42e5a4109'
down_revision = '849bf8cfb979'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('protocol_version',
    sa.Column('updated_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_by', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('protocol_id', sa.Integer(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['protocol_id'], ['protocol.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('run_version',
    sa.Column('updated_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_by', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_version',
    sa.Column('updated_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_by', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('protocol', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('protocol', sa.Column('version_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'protocol', 'protocol_version', ['version_id'], ['id'], use_alter=True)
    op.drop_column('protocol', 'updated_on')
    op.drop_column('protocol', 'updated_by')
    op.drop_column('protocol', 'data')
    op.add_column('run', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('run', sa.Column('protocol_version_id', sa.Integer(), nullable=True))
    op.add_column('run', sa.Column('version_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'run', 'protocol_version', ['protocol_version_id'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'run', 'run_version', ['version_id'], ['id'], use_alter=True)
    op.drop_column('run', 'updated_on')
    op.drop_column('run', 'updated_by')
    op.drop_column('run', 'data')
    op.add_column('user', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('version_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'user_version', ['version_id'], ['id'], use_alter=True)
    op.drop_column('user', 'updated_on')
    op.drop_column('user', 'updated_by')
    op.drop_column('user', 'data')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('updated_by', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('updated_on', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'version_id')
    op.drop_column('user', 'is_deleted')
    op.add_column('run', sa.Column('data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('run', sa.Column('updated_by', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.add_column('run', sa.Column('updated_on', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'run', type_='foreignkey')
    op.drop_constraint(None, 'run', type_='foreignkey')
    op.drop_column('run', 'version_id')
    op.drop_column('run', 'protocol_version_id')
    op.drop_column('run', 'is_deleted')
    op.add_column('protocol', sa.Column('data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('protocol', sa.Column('updated_by', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.add_column('protocol', sa.Column('updated_on', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'protocol', type_='foreignkey')
    op.drop_column('protocol', 'version_id')
    op.drop_column('protocol', 'is_deleted')
    op.drop_table('user_version')
    op.drop_table('run_version')
    op.drop_table('protocol_version')
    # ### end Alembic commands ###
