"""Initial migration.

Revision ID: 5a6f225a78e3
Revises: 
Create Date: 2020-06-30 06:50:51.791209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a6f225a78e3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compound',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('compound_id', sa.String(length=256), nullable=True),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.Column('target_id', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('derivation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('formula', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('protocol',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('protocol_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=512), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('data_link', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['protocol_id'], ['protocol.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('derived_layer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('derivation_id', sa.Integer(), nullable=True),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=True),
    sa.Column('formula', sa.String(length=512), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('column_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['derivation_id'], ['derivation.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('value_layer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('column_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sample_value',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value_layer_id', sa.Integer(), nullable=True),
    sa.Column('derived_layer_id', sa.Integer(), nullable=True),
    sa.Column('compound_id', sa.Integer(), nullable=True),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('sample_id', sa.Integer(), nullable=False),
    sa.Column('row', sa.Integer(), nullable=False),
    sa.Column('column', sa.Integer(), nullable=False),
    sa.Column('value', sa.Numeric(precision=64, scale=32), nullable=True),
    sa.ForeignKeyConstraint(['compound_id'], ['compound.id'], ),
    sa.ForeignKeyConstraint(['derived_layer_id'], ['derived_layer.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['run.id'], ),
    sa.ForeignKeyConstraint(['value_layer_id'], ['value_layer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sample_value')
    op.drop_table('value_layer')
    op.drop_table('derived_layer')
    op.drop_table('run')
    op.drop_table('protocol')
    op.drop_table('derivation')
    op.drop_table('compound')
    # ### end Alembic commands ###
