"""Add ON DELETE CASCADE to tables.

Revision ID: 5d1a156b1e81
Revises: 3643538ae6b5
Create Date: 2020-12-20 08:06:55.142587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d1a156b1e81'
down_revision = '3643538ae6b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('protocol_version_protocol_id_fkey', 'protocol_version', type_='foreignkey')
    op.create_foreign_key(None, 'protocol_version', 'protocol', ['protocol_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('run_version_run_id_fkey', 'run_version', type_='foreignkey')
    op.create_foreign_key(None, 'run_version', 'run', ['run_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('user_version_user_id_fkey', 'user_version', type_='foreignkey')
    op.create_foreign_key(None, 'user_version', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_version', type_='foreignkey')
    op.create_foreign_key('user_version_user_id_fkey', 'user_version', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'run_version', type_='foreignkey')
    op.create_foreign_key('run_version_run_id_fkey', 'run_version', 'run', ['run_id'], ['id'])
    op.drop_constraint(None, 'protocol_version', type_='foreignkey')
    op.create_foreign_key('protocol_version_protocol_id_fkey', 'protocol_version', 'protocol', ['protocol_id'], ['id'])
    # ### end Alembic commands ###
