"""Adds user table.

Revision ID: 849bf8cfb979
Revises: d8ed0a220a5a
Create Date: 2020-10-25 00:20:54.021846

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '849bf8cfb979'
down_revision = 'd8ed0a220a5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=64), nullable=True),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('run_permission')
    op.drop_table('protocol_permission')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('protocol_permission',
    sa.Column('created_on', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('updated_on', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('protocol_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['protocol_id'], ['protocol.id'], name='protocol_permission_protocol_id_fkey'),
    sa.PrimaryKeyConstraint('protocol_id', 'user_id', name='protocol_permission_pkey')
    )
    op.create_table('run_permission',
    sa.Column('created_on', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('updated_on', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('run_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['run.id'], name='run_permission_run_id_fkey'),
    sa.PrimaryKeyConstraint('run_id', 'user_id', name='run_permission_pkey')
    )
    op.drop_table('user')
    # ### end Alembic commands ###
