"""Switch from server_default to default for base models p2.

Revision ID: 9895123c372c
Revises: a4003b02bcf7
Create Date: 2020-11-11 09:51:14.346020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9895123c372c'
down_revision = 'a4003b02bcf7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('protocol', sa.Column('created_on', sa.DateTime(), nullable=True))
    op.add_column('protocol_version', sa.Column('updated_on', sa.DateTime(), nullable=True))
    op.add_column('run', sa.Column('created_on', sa.DateTime(), nullable=True))
    op.add_column('run_version', sa.Column('updated_on', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('created_on', sa.DateTime(), nullable=True))
    op.add_column('user_version', sa.Column('updated_on', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_version', 'updated_on')
    op.drop_column('user', 'created_on')
    op.drop_column('run_version', 'updated_on')
    op.drop_column('run', 'created_on')
    op.drop_column('protocol_version', 'updated_on')
    op.drop_column('protocol', 'created_on')
    # ### end Alembic commands ###
