"""Adds user permissions to demo_run.

Revision ID: ad19827e762c
Revises: 2bee1dfc00e3
Create Date: 2020-07-12 23:17:25.076125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad19827e762c'
down_revision = '2bee1dfc00e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('demo_run_permission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('demo_run_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['demo_run_id'], ['demo_run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('demo_run_permission')
    # ### end Alembic commands ###
