FROM node:14-alpine AS builder

# For node-gyp.
RUN apk update && apk add python make gcc g++

# Build webapp bundle.
WORKDIR /app
COPY package.json package.json
COPY package-lock.json package-lock.json
RUN npm install
COPY . .

CMD ["npm", "start"]
